const letterImageMap = {
	a: require('../assets/sign-characters/a.png'),
	b: require('../assets/sign-characters/b.png'),
	c: require('../assets/sign-characters/c.png'),
	d: require('../assets/sign-characters/d.png'),
	e: require('../assets/sign-characters/e.png'),
	f: require('../assets/sign-characters/f.png'),
	g: require('../assets/sign-characters/g.png'),
	h: require('../assets/sign-characters/h.png'),
	i: require('../assets/sign-characters/i.png'),
	j: require('../assets/sign-characters/j.png'),
	k: require('../assets/sign-characters/k.png'),
	l: require('../assets/sign-characters/l.png'),
	m: require('../assets/sign-characters/m.png'),
	n: require('../assets/sign-characters/n.png'),
	o: require('../assets/sign-characters/o.png'),
	p: require('../assets/sign-characters/p.png'),
	q: require('../assets/sign-characters/q.png'),
	r: require('../assets/sign-characters/r.png'),
	s: require('../assets/sign-characters/s.png'),
	t: require('../assets/sign-characters/t.png'),
	u: require('../assets/sign-characters/u.png'),
	v: require('../assets/sign-characters/v.png'),
	w: require('../assets/sign-characters/w.png'),
	x: require('../assets/sign-characters/x.png'),
	y: require('../assets/sign-characters/y.png'),
	z: require('../assets/sign-characters/z.png'),
	"0": require('../assets/sign-characters/0.png'),
	"1": require('../assets/sign-characters/1.png'),
	"2": require('../assets/sign-characters/2.png'),
	"3": require('../assets/sign-characters/3.png'),
	"4": require('../assets/sign-characters/4.png'),
	"5": require('../assets/sign-characters/5.png'),
	"6": require('../assets/sign-characters/6.png'),
	"7": require('../assets/sign-characters/7.png'),
	"8": require('../assets/sign-characters/8.png'),
	"9": require('../assets/sign-characters/9.png'),
}

export default letterImageMap;